package com.example.optimusnotes.screens

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.Saver
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.unit.dp
import com.example.optimusnotes.MyColorPicker
import com.example.optimusnotes.roomdb.Note
import com.example.optimusnotes.viewmodel.NoteViewModel

@Composable
fun DisplayDialog(viewModel: NoteViewModel, showDialog: Boolean, onDismiss: () -> Unit) {
    // Create a custom Saver for Color
    val colorSaver = Saver<Color, Int>(
        save = { color -> color.toArgb() },
        restore = { argb -> Color(argb) }
    )

    // State management with rememberSaveable
    var title by rememberSaveable { mutableStateOf("") }
    var description by rememberSaveable { mutableStateOf("") }
    var selectedColor by rememberSaveable(stateSaver = colorSaver) {
        mutableStateOf(Color.Cyan)
    }

    if (showDialog) {
        AlertDialog(
            onDismissRequest = onDismiss,
            title = { Text(text = "Add Note") },
            text = {
                Column(modifier = Modifier.padding(8.dp)) {
                    TextField(
                        value = title,
                        onValueChange = { title = it },
                        label = { Text(text = "Title") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )

                    Spacer(modifier = Modifier.height(8.dp))

                    TextField(
                        value = description,
                        onValueChange = { description = it },
                        label = { Text(text = "Description") },
                        modifier = Modifier.fillMaxWidth()
                    )

                    Spacer(modifier = Modifier.height(12.dp))

                    Text(text = "Select Color", style = MaterialTheme.typography.bodyMedium)
                    MyColorPicker(selectedColor = selectedColor) { selectedColor = it }
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        if (title.isNotBlank()) {
                            // Create note with timestamp
                            val note = Note(
                                id = 0, // ID will be auto-generated by Room
                                title = title,
                                description = description,
                                color = selectedColor.toArgb(),
                                timestamp = System.currentTimeMillis(), // Set the current timestamp
                                content = "", // Empty content for now
                                folderName = "Uncategorized" // Folder can be dynamic
                            )
                            viewModel.insert(note)
                            onDismiss() // Close dialog after saving
                        }
                    },
                    enabled = title.isNotBlank() // Prevent empty notes
                ) {
                    Text(text = "Save")
                }
            },
            dismissButton = {
                Button(onClick = onDismiss) {
                    Text(text = "Cancel")
                }
            }
        )
    }
}
